baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '复盘文档'
theme = "book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    style = "monokailight"
    tabWidth = 2

